baikal-server:
  image: sheedy/baikal
  ports:
   - "32777:80"
  # volumes:
  # - ./db/:/usr/share/nginx/html/baikal-regular/Specific/db/
  # command: python manage.py runserver 0.0.0.0:8000

#   links:
#    - redis
# redis:
#   image: redis
#
# docker cp db.sqlite baikalserver_baikal-server_1:/usr/share/nginx/html/baikal-regular/Specific/db/db.sqlite
# docker cp baikalserver_baikal-server_1:/usr/share/nginx/html/baikal-regular/Specific/db/db.sqlite db.sqlite